version: "3.8"

services:
  # PostgreSQL Database with PostGIS
  database:
    image: postgis/postgis:15-3.3
    container_name: mars-gis-db
    environment:
      POSTGRES_DB: mars_gis
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mars-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mars_user -d mars_gis"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: mars-gis-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - mars-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mars-gis-backend
    environment:
      - DATABASE_URL=postgresql://mars_user:mars_password@database:5432/mars_gis
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=false
      - ALLOWED_HOSTS=localhost,127.0.0.1,frontend
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mars-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mars-gis-frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api/v1
      - REACT_APP_WS_URL=ws://localhost/ws
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mars-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Background Worker for AI/ML tasks
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mars-gis-worker
    command:
      [
        "python",
        "-m",
        "celery",
        "worker",
        "-A",
        "mars_gis.core.celery",
        "--loglevel=info",
      ]
    environment:
      - DATABASE_URL=postgresql://mars_user:mars_password@database:5432/mars_gis
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=false
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mars-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-m",
          "celery",
          "inspect",
          "ping",
          "-A",
          "mars_gis.core.celery",
        ]
      interval: 60s
      timeout: 30s
      retries: 3

  # Celery Beat Scheduler
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mars-gis-scheduler
    command:
      [
        "python",
        "-m",
        "celery",
        "beat",
        "-A",
        "mars_gis.core.celery",
        "--loglevel=info",
      ]
    environment:
      - DATABASE_URL=postgresql://mars_user:mars_password@database:5432/mars_gis
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=false
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mars-network
    restart: unless-stopped

  # Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: mars-gis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      - mars-network
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: mars-gis-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - mars-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  mars-network:
    driver: bridge
