# MARS-GIS Dockerfile - MOVED
# New locations:
#   docker/backend/Dockerfile   (Backend API)
#   docker/frontend/Dockerfile  (Frontend React)
# Use: ./docker/docker-helper.sh dev|prod|build

FROM alpine:latest
RUN echo "Docker files moved to docker/ directory"
RUN echo "Use: ./docker/docker-helper.sh help"
CMD ["echo", "Use ./docker/docker-helper.sh help"]
